apiVersion: apps/v1
kind: Deployment
metadata:
    name: kraken-trades-deployment
    labels:
        app: kraken-trades
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kraken-trades
    template:
        metadata:
            labels:
                app: kraken-trades

        spec:
            containers:
            - name: kraken-trades
              image: docker.rldsoftware.nl/kraken-trades:v3

